/* Kútfő Plusz ERP – Géppark
 * ÚJ, EGYETLEN CRUD. Az Anyag/Raktár mintáját követi:
 * render -> közvetlen onclick -> modal -> save -> render.
 */
(function(){
'use strict';
const TYPES={auto:'Autó / jármű',furo:'Fúrógép',kompresszor:'Kompresszor',teherauto:'Teherautó',utanfuto:'Utánfutó',egyeb:'Egyéb'};
const STATUS=['Üzemképes','Szervizre vár','Meghibásodott','Üzemen kívül'];
const FUELS=[['','—'],['diesel','Dízel'],['petrol','Benzin'],['electric','Elektromos'],['hybrid','Hibrid'],['other','Egyéb']];
const TABS=[['base','Általános'],['tech','Műszaki'],['docs','Okmányok'],['service','Szerviz'],['cost','Költségek'],['notes','Megjegyzés']];
const root=()=>document.getElementById('content')||document.querySelector('.content');
const machines=()=>{db.machines=Array.isArray(db.machines)?db.machines:[];return db.machines};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(m,k,d='')=>m&&m[k]!==undefined&&m[k]!==null&&m[k]!==''?m[k]:d;
const num=v=>Number(v)||0;
const money=v=>v===null||v===undefined||v===''?'—':num(v).toLocaleString('hu-HU')+' Ft';
function fresh(){return {id:typeof uid==='function'?uid('G'):'G-'+Date.now(),name:'',asset_type:'egyeb',asset_code:'',make:'',model:'',year:0,plate:'',vin:'',engine_no:'',purchase_date:'',purchase_value:0,current_value:0,status:'Üzemképes',odometer:0,hours:0,service_km:0,service_hours:0,service_date:'',fuel:'',engine_cc:0,power_hp:0,power_kw:0,transmission:'',drive:'',body:'',color:'',tire_size:'',weight:0,gvw:0,mot_expiry:'',insurance_expiry:'',casco_expiry:'',toll_expiry:'',registration_doc:'',insurer:'',policy_no:'',last_service_date:'',last_service_meter:'',service_provider:'',last_service_cost:0,service_note:'',fuel_cost_month:0,service_cost_year:0,insurance_cost_year:0,other_cost_year:0,responsible:'',notes:''};}
function field(label,k,m,type='text'){return `<div class="field"><label>${label}</label><input class="input" data-k="${k}" type="${type}" value="${esc(val(m,k,''))}"></div>`;}
function select(label,k,m,opts){return `<div class="field"><label>${label}</label><select class="select" data-k="${k}">${opts.map(o=>`<option value="${esc(o[0])}" ${String(val(m,k,''))===String(o[0])?'selected':''}>${esc(o[1])}</option>`).join('')}</select></div>`;}
function tabHtml(m,t){
 if(t==='base')return `<div class="formgrid">${field('Eszköz neve','name',m)}${select('Eszköztípus','asset_type',m,Object.entries(TYPES))}${field('Belső azonosító','asset_code',m)}${field('Gyártó','make',m)}${field('Típus / modell','model',m)}${field('Évjárat','year',m,'number')}${field('Rendszám','plate',m)}${field('Alvázszám (VIN)','vin',m)}${field('Motorszám','engine_no',m)}${field('Beszerzés dátuma','purchase_date',m,'date')}${field('Beszerzési érték (Ft)','purchase_value',m,'number')}${field('Jelenlegi érték (Ft)','current_value',m,'number')}${select('Állapot','status',m,STATUS.map(x=>[x,x]))}</div>`;
 if(t==='tech')return `<div class="formgrid">${field('Kilométeróra (km)','odometer',m,'number')}${field('Üzemóra','hours',m,'number')}${field('Következő szerviz km','service_km',m,'number')}${field('Következő szerviz üzemóra','service_hours',m,'number')}${field('Következő szerviz dátuma','service_date',m,'date')}${select('Üzemanyag','fuel',m,FUELS)}${field('Hengerűrtartalom (cm³)','engine_cc',m,'number')}${field('Teljesítmény (LE)','power_hp',m,'number')}${field('Teljesítmény (kW)','power_kw',m,'number')}${field('Sebességváltó','transmission',m)}${field('Meghajtás','drive',m)}${field('Karosszéria / kivitel','body',m)}${field('Szín','color',m)}${field('Gumiabroncs méret','tire_size',m)}${field('Saját tömeg (kg)','weight',m,'number')}${field('Megengedett össztömeg (kg)','gvw',m,'number')}</div>`;
 if(t==='docs')return `<div class="formgrid">${field('Műszaki vizsga lejárata','mot_expiry',m,'date')}${field('Kötelező biztosítás lejárata','insurance_expiry',m,'date')}${field('Casco lejárata','casco_expiry',m,'date')}${field('Útdíj / matrica lejárata','toll_expiry',m,'date')}${field('Forgalmi dokumentum','registration_doc',m)}${field('Biztosító','insurer',m)}${field('Biztosítás kötvényszáma','policy_no',m)}</div>`;
 if(t==='service')return `<div class="formgrid">${field('Utolsó szerviz dátuma','last_service_date',m,'date')}${field('Utolsó szerviz km / üzemóra','last_service_meter',m)}${field('Szervizhely / szerelő','service_provider',m)}${field('Utolsó szerviz költsége (Ft)','last_service_cost',m,'number')}<div class="field full"><label>Következő szerviz megjegyzés</label><textarea class="textarea" data-k="service_note">${esc(val(m,'service_note',''))}</textarea></div></div>`;
 if(t==='cost')return `<div class="formgrid">${field('Havi átlagos üzemanyagköltség (Ft)','fuel_cost_month',m,'number')}${field('Éves szervizköltség (Ft)','service_cost_year',m,'number')}${field('Éves biztosítási költség (Ft)','insurance_cost_year',m,'number')}${field('Egyéb éves költség (Ft)','other_cost_year',m,'number')}</div>`;
 return `<div class="formgrid"><div class="field full"><label>Felelős / használó</label><input class="input" data-k="responsible" value="${esc(val(m,'responsible',''))}"></div><div class="field full"><label>Megjegyzés</label><textarea class="textarea" data-k="notes">${esc(val(m,'notes',''))}</textarea></div></div>`;
}
function read(box,m){box.querySelectorAll('[data-k]').forEach(e=>m[e.dataset.k]=e.type==='number'?(Number(e.value)||0):e.value.trim());return m;}
async function saveData(){if(typeof save!=='function')throw new Error('A központi mentési rendszer nem érhető el.');const r=save();if(r&&typeof r.then==='function')await r;}
function modal(title,m,isNew){let active='base';const x=document.createElement('div');x.className='modal';x.innerHTML=`<div class="modalbox" style="max-width:980px"><div class="modalhead"><h2>${title}</h2><button type="button" class="icon" id="mf_close">×</button></div><div class="modalbody"><div class="fleet-tabs">${TABS.map((t,i)=>`<button type="button" class="btn secondary mf_tab${i===0?' active':''}" data-tab="${t[0]}">${t[1]}</button>`).join('')}</div><div id="mf_pane">${tabHtml(m,active)}</div><div class="modalfoot">${isNew?'':'<button type="button" class="btn danger" id="mf_delete">Törlés</button>'}<span style="flex:1"></span><button type="button" class="btn secondary" id="mf_cancel">Mégse</button><button type="button" class="btn" id="mf_save">Mentés</button></div></div></div>`;document.body.appendChild(x);
 const close=()=>x.remove();x.querySelector('#mf_close').onclick=close;x.querySelector('#mf_cancel').onclick=close;
 x.querySelectorAll('.mf_tab').forEach(b=>b.onclick=()=>{read(x,m);active=b.dataset.tab;x.querySelectorAll('.mf_tab').forEach(t=>t.classList.toggle('active',t===b));x.querySelector('#mf_pane').innerHTML=tabHtml(m,active);});
 if(!isNew)x.querySelector('#mf_delete').onclick=()=>{if(!confirm(`Biztosan törlöd a(z) „${m.name}” eszközt?`))return;const i=machines().indexOf(m);if(i>=0)machines().splice(i,1);saveData().then(()=>{close();render();}).catch(e=>alert('A törlés mentése nem sikerült: '+e.message));};
 x.querySelector('#mf_save').onclick=async()=>{read(x,m);if(!m.name){alert('Az eszköz neve kötelező.');return;}try{if(isNew)machines().push(m);await saveData();close();render();if(typeof toast==='function')toast(isNew?'Eszköz létrehozva':'Eszköz módosítva');}catch(e){if(isNew){const i=machines().indexOf(m);if(i>=0)machines().splice(i,1);}alert('A mentés nem sikerült: '+e.message);}};
}
function create(){modal('Új eszköz',fresh(),true);}
function edit(id){const m=machines().find(x=>String(x.id)===String(id));if(m)modal('Eszköz szerkesztése',m,false);}
function profile(id){const m=machines().find(x=>String(x.id)===String(id));if(!m)return;const r=root();if(!r)return;const rows=(pairs)=>pairs.map(([a,b])=>`<div class="kpi"><span>${esc(a)}</span><b>${esc(b===''||b===null||b===undefined?'—':b)}</b></div>`).join('');r.innerHTML=`<div class="panel"><div class="panelhead"><div><div class="eyebrow">GÉPPARK / ADATLAP</div><h2>${esc(m.name)}</h2><div class="label">${esc(TYPES[m.asset_type]||'Egyéb')} · ${esc(m.make||'')} ${esc(m.model||'')}</div></div><div><button type="button" class="btn secondary" onclick="window.__fleetBack()">← Vissza</button> <button type="button" class="btn" onclick="window.__fleetEdit('${esc(m.id)}')">Szerkesztés</button></div></div><div class="fleet-tabs"><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('base')">Általános</button><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('tech')">Műszaki</button><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('docs')">Okmányok</button><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('service')">Szerviz</button><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('cost')">Költségek</button><button type="button" class="btn secondary" onclick="window.__fleetProfileTab('notes')">Megjegyzés</button></div><div id="fleet_profile_pane">${rows([['Eszköz neve',m.name],['Eszköztípus',TYPES[m.asset_type]||m.asset_type],['Belső azonosító',m.asset_code],['Gyártó',m.make],['Típus / modell',m.model],['Évjárat',m.year],['Rendszám',m.plate],['VIN',m.vin],['Motorszám',m.engine_no],['Beszerzési érték',money(m.purchase_value)],['Jelenlegi érték',money(m.current_value)],['Állapot',m.status]])}</div></div>`;
 window.__fleetProfileTab=t=>{let p=[];if(t==='tech')p=[['Kilométeróra',num(m.odometer)+' km'],['Üzemóra',num(m.hours)+' h'],['Következő szerviz km',num(m.service_km)+' km'],['Következő szerviz üzemóra',num(m.service_hours)+' h'],['Következő szerviz dátuma',m.service_date],['Üzemanyag',FUELS.find(x=>x[0]===m.fuel)?.[1]||m.fuel],['Hengerűrtartalom',num(m.engine_cc)+' cm³'],['Teljesítmény',num(m.power_hp)+' LE / '+num(m.power_kw)+' kW'],['Sebességváltó',m.transmission],['Meghajtás',m.drive],['Karosszéria / kivitel',m.body],['Szín',m.color],['Gumiabroncs',m.tire_size],['Saját tömeg',num(m.weight)+' kg'],['Megengedett össztömeg',num(m.gvw)+' kg']];else if(t==='docs')p=[['Műszaki vizsga lejárata',m.mot_expiry],['Biztosítás lejárata',m.insurance_expiry],['Casco lejárata',m.casco_expiry],['Útdíj / matrica',m.toll_expiry],['Forgalmi dokumentum',m.registration_doc],['Biztosító',m.insurer],['Kötvényszám',m.policy_no]];else if(t==='service')p=[['Utolsó szerviz',m.last_service_date],['Utolsó szerviz km / óra',m.last_service_meter],['Szervizhely',m.service_provider],['Utolsó szerviz költsége',money(m.last_service_cost)],['Megjegyzés',m.service_note]];else if(t==='cost')p=[['Havi üzemanyagköltség',money(m.fuel_cost_month)],['Éves szervizköltség',money(m.service_cost_year)],['Éves biztosítás',money(m.insurance_cost_year)],['Egyéb éves költség',money(m.other_cost_year)]];else if(t==='notes')p=[['Felelős / használó',m.responsible],['Megjegyzés',m.notes]];else p=[['Eszköz neve',m.name],['Eszköztípus',TYPES[m.asset_type]||m.asset_type],['Belső azonosító',m.asset_code],['Gyártó',m.make],['Típus / modell',m.model],['Évjárat',m.year],['Rendszám',m.plate],['VIN',m.vin],['Motorszám',m.engine_no],['Beszerzési érték',money(m.purchase_value)],['Jelenlegi érték',money(m.current_value)],['Állapot',m.status]];document.getElementById('fleet_profile_pane').innerHTML=rows(p);};
 window.__fleetBack=()=>{if(typeof current!=='undefined')current='machines';render();};window.__fleetEdit=edit;
}
function view(){const rows=machines();return `<div class="panel"><div class="panelhead"><div><h2>Géppark</h2><div class="label">Járművek, fúrógépek, kompresszorok és egyéb eszközök</div></div><button type="button" class="btn" onclick="window.__fleetCreate()">+ Új eszköz</button></div><div class="tablewrap"><table class="table"><thead><tr><th>ESZKÖZ</th><th>TÍPUS</th><th>AZONOSÍTÓ</th><th>KM / ÜZEMÓRA</th><th>ÁLLAPOT</th><th>MŰVELETEK</th></tr></thead><tbody>${rows.length?rows.map(m=>`<tr><td><b>${esc(m.name||'Névtelen eszköz')}</b><div class="label">${esc((m.make||'')+' '+(m.model||''))}</div></td><td>${esc(TYPES[m.asset_type]||m.asset_type||'Egyéb')}</td><td>${esc(m.plate||m.asset_code||'—')}</td><td>${m.odometer?num(m.odometer).toLocaleString('hu-HU')+' km':num(m.hours).toLocaleString('hu-HU')+' h'}</td><td>${esc(m.status||'Üzemképes')}</td><td><button type="button" class="btn secondary small" onclick="window.__fleetProfile('${esc(m.id)}')">Adatlap</button> <button type="button" class="btn secondary small" onclick="window.__fleetEdit('${esc(m.id)}')">Szerkesztés</button> <button type="button" class="btn danger small" onclick="window.__fleetDelete('${esc(m.id)}')">Törlés</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">Nincs eszköz a gépparkban.</td></tr>'}</tbody></table></div></div>`;}
window.__fleetCreate=create;window.__fleetEdit=edit;window.__fleetProfile=profile;window.__fleetDelete=async id=>{const m=machines().find(x=>String(x.id)===String(id));if(!m||!confirm(`Biztosan törlöd a(z) „${m.name}” eszközt?`))return;const i=machines().indexOf(m);machines().splice(i,1);try{await saveData();render();}catch(e){machines().splice(i,0,m);alert('A törlés nem sikerült: '+e.message);}};
function install(){if(typeof views==='undefined'||typeof db==='undefined'||typeof render!=='function')return false;views.machines=view;return true;}
let n=0;(function boot(){if(install())return;if(n++<40)setTimeout(boot,250);})();
})();
