/* Kútfő Plusz ERP 2.0 — quote UI/DOCX compatibility layer */
(function(){
  "use strict";
  const PATCH="ERP2.0-QUOTE-RUNTIME-FIX-2026-08-30-09";
  const getItems=()=>{try{if(typeof quoteItems!=="undefined"&&Array.isArray(quoteItems))return quoteItems;}catch(e){}return Array.isArray(window.quoteItems)?window.quoteItems:null;};
  const num=v=>{const n=Number(String(v??"").replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0;};
  function projectPermitDiameter(p){try{const w=p?.well||{},secs=Array.isArray(w.casingSections)?w.casingSections:[];for(const sec of secs){for(const raw of [sec?.diameter,sec?.pipeDiameter,sec?.casingDiameter,sec?.technicalData,sec?.technical,sec?.spec,sec?.[3]]){const s=String(raw??"").replace(/,/g,".");let m=s.match(/(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)\s*Ø?\s*mm/i);if(m)return m[1].replace(/\s+/g,"");m=s.match(/(?:Ø\s*)?(\d+(?:\.\d+)?)\s*mm/i);if(m)return m[1];}}for(const raw of [p?.name,p?.title,p?.description]){const s=String(raw??"").replace(/,/g,".");let m=s.match(/(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)\s*Ø?\s*mm/i);if(m)return m[1].replace(/\s+/g,"");m=s.match(/(?:Ø\s*)?(\d+(?:\.\d+)?)\s*mm/i);if(m)return m[1];}return String(w.casingDiameter??p?.casingDiameter??"").replace(/,/g,".").replace(/\s+/g,"");}catch(e){return "";}}
  function canonicalMaterialIdentity(m){const s=String(m?.name??"");const d=(s.match(/(\d+(?:\.\d+)?(?:\s*\/\s*\s*\d+(?:\.\d+)?)?)\s*mm/i)||[])[1];if(!d)return "";const role=/szűr|szuro|filter/i.test(s)?"FILTER":"BLANK";return `CASING|${d.replace(/\s+/g,"")}|${role}`;}
  function ensurePipeCatalogIdentity(){try{if(!Array.isArray(db?.materials))return{};const index={};db.materials.forEach(m=>{const key=m?.materialKey||canonicalMaterialIdentity(m);if(!key)return;if(!m.materialKey)m.materialKey=key;if(/^CASING\|/.test(key)&&!m.casingMaterialKey)m.casingMaterialKey=key;m.priceSource=num(m.price)>0?"catalog-exact":"catalog-missing";index[key]=m;});window.KUTFOPLUSZ_PIPE_CATALOG_INDEX=index;return index;}catch(e){return{};}}
  function currentProject(){try{let id=window.projectPageId||db?.ui?.openProjectId;if(!id){const h=String(location.hash||"").replace(/^#\//,"");if(h.startsWith("project/"))id=decodeURIComponent(h.split("/")[1]||"");}return id&&Array.isArray(db?.projects)?db.projects.find(p=>String(p.id)===String(id))||null:null;}catch(e){return null;}}
  function normalizeProjectIds(){try{if(!Array.isArray(db?.projects))return;let changed=false;db.projects.forEach(p=>{if(p&&p.id!=null&&typeof p.id!=="string"){p.id=String(p.id);changed=true;}});if(changed&&typeof save==="function")save();}catch(e){}}
  function normalizeProjectUi(){const p=currentProject(),box=document.querySelector(".project-hero-kpis");if(!p||!box)return;const cards=[...box.querySelectorAll(":scope > .card")];if(cards.length<4)return;const q=(db.quotes||[]).filter(x=>String(x.projectId||"")===String(p.id)&&String(x.status||"")==="Elfogadva").pop();const net=q?(num(q.net)||num(q.netTotal)||((q.items||[]).reduce((s,x)=>s+num(x.qty??x.quantity)*num(x.price),0))):num(p.value);const cost=num(p.cost),vals=[`${num(p.progress)}%`,typeof money==="function"?money(net):`${net.toLocaleString("hu-HU")} Ft`,typeof money==="function"?money(cost):`${cost.toLocaleString("hu-HU")} Ft`,typeof money==="function"?money(net-cost):`${(net-cost).toLocaleString("hu-HU")} Ft`],labs=["Készültség","Szerződéses érték","Tényleges költség","Fedezet"];cards.forEach((c,i)=>{c.querySelector(".label")&&(c.querySelector(".label").textContent=labs[i]);c.querySelector(".value")&&(c.querySelector(".value").textContent=vals[i]);});}
  function syncQuoteDiameterFromProject(){try{const el=document.getElementById("q_pipe_diameter"),pe=document.getElementById("q_project");if(!el||!pe)return;const p=(db.projects||[]).find(x=>String(x.id)===String(pe.value||""));const d=projectPermitDiameter(p);if(!d)return;if(el.tagName==="SELECT"){let o=[...el.options].find(x=>String(x.dataset.fullDiameter||x.value)===d||String(x.value)===d.split("/")[0]);if(!o){o=document.createElement("option");el.appendChild(o);}o.value=d.split("/")[0];o.textContent=`Ø ${d} mm`;o.dataset.fullDiameter=d;el.value=o.value;}else el.value=d;el.dispatchEvent(new Event("change",{bubbles:true}));}catch(e){}}
  function syncQuoteCasingItemsFromProject(){try{const items=getItems(),pe=document.getElementById("q_project");if(!items||!pe)return;const p=(db.projects||[]).find(x=>String(x.id)===String(pe.value||"")),secs=Array.isArray(p?.well?.casingSections)?p.well.casingSections:[];if(!secs.length)return;const d=projectPermitDiameter(p)||"324";const meters=type=>secs.filter(s=>/szűr|szuro|filter/i.test(String(s?.type??s?.[2]))===/szűr|szuro|filter/i.test(type)).reduce((a,s)=>a+Math.max(0,num(s?.to??s?.[1])-num(s?.from??s?.[0])),0);const upsert=(tag,name,m)=>{if(m<=0)return;let x=items.find(i=>i?.[tag]);if(!x){x={desc:name,description:name,name,qty:m,quantity:m,unit:"m",price:0};items.push(x);}x[tag]=true;x.qty=m;x.quantity=m;x.unit="m";x.desc=x.desc||name;x.name=x.name||name;};upsert("__KPF_CASING_BLANK",`PVC béléscső Ø${d} mm`,meters("Vak"));upsert("__KPF_CASING_FILTER",`PVC szűrőcső Ø${d} mm`,meters("Szűrő"));}catch(e){}}
  function hydrateQuoteItemsFromDb(id){try{const items=getItems();if(!items||!id||!Array.isArray(db?.quotes))return;const q=db.quotes.find(x=>String(x.id)===String(id));if(!q||!Array.isArray(q.items)||!q.items.length)return;const saved=q.items.map(x=>({desc:String(x?.desc??x?.description??""),qty:num(x?.qty??x?.quantity),unit:String(x?.unit??"db"),price:num(x?.price??x?.unitPrice),priceManual:x?.priceManual===true}));const sameShape=items.length===saved.length&&items.every((x,i)=>String(x?.desc??"").trim()===String(saved[i]?.desc??"").trim()&&num(x?.qty??x?.quantity)===num(saved[i]?.qty??saved[i]?.quantity));const broken=sameShape&&items.some((x,i)=>num(x?.price)===0&&num(saved[i]?.price)>0);if(!items.length||broken||!items.some(x=>String(x?.desc??"").trim()||num(x?.qty??x?.quantity)||num(x?.price))){items.splice(0,items.length,...saved);}}catch(e){console.warn("Quote item hydrate:",e);}}
  function installDocxModelGuard(){if(window.__KPF_DOCX_GUARD||typeof window.collectQuoteTemplate!=="function")return;window.__KPF_DOCX_GUARD=true;const original=window.collectQuoteTemplate;window.collectQuoteTemplate=function(){try{hydrateQuoteItemsFromDb(window.editingQuoteId);const items=getItems(),q=(db?.quotes||[]).find(x=>String(x.id)===String(window.editingQuoteId));if(items&&q?.items)q.items.forEach((saved,i)=>{const cur=items[i];if(cur&&num(cur.price)===0&&num(saved.price)>0){cur.price=num(saved.price);cur.priceManual=saved.priceManual===true;}});}catch(e){}const model=original.apply(this,arguments);try{const q=(db?.quotes||[]).find(x=>String(x.id)===String(window.editingQuoteId));if(q?.items&&model?.items)model.items.forEach((x,i)=>{const s=q.items[i];if(s&&num(x.price)===0&&num(s.price)>0)x.price=num(s.price);if(s&&num(x.qty)===0&&num(s.qty)>0)x.qty=num(s.qty);if(s&&x.unit!==s.unit)x.unit=s.unit;});}catch(e){}return model;};}
  function patchExport(){if(window.__KPF_EXPORT||typeof window.exportQuoteDoc!=="function")return;window.__KPF_EXPORT=true;const original=window.exportQuoteDoc;window.exportQuoteDoc=function(){try{const q=(db?.quotes||[]).find(x=>String(x.id)===String(window.editingQuoteId));if(q){hydrateQuoteItemsFromDb(q.id);if(q.customerId!=null)window.customerId=q.customerId;}}catch(e){}return original.apply(this,arguments);};}
  function patchEditors(){if(window.__KPF_EDITORS)return;window.__KPF_EDITORS=true;if(typeof window.editQuote==="function"){const o=window.editQuote;window.editQuote=function(id){window.editingQuoteId=id;const r=o.apply(this,arguments);setTimeout(()=>hydrateQuoteItemsFromDb(id),150);setTimeout(()=>hydrateQuoteItemsFromDb(id),650);return r;};}if(typeof window.openQuoteEditorPage==="function"){const o=window.openQuoteEditorPage;window.openQuoteEditorPage=function(){const id=arguments[0];window.editingQuoteId=id;const r=o.apply(this,arguments);setTimeout(()=>{hydrateQuoteItemsFromDb(id);syncQuoteDiameterFromProject();syncQuoteCasingItemsFromProject();},100);setTimeout(()=>hydrateQuoteItemsFromDb(id),600);return r;};}}
  function removePreviewControls(){document.querySelectorAll("button,a").forEach(el=>{if(/Előnézet\s*\/\s*PDF|PDF\s*\/\s*Nyomtatás|Nyomtatás\s*\/\s*PDF/i.test(String(el.textContent||"").replace(/\s+/g," ").trim()))el.remove();});}
  function disablePreviewFunctions(){if(typeof window.previewQuote==="function")window.previewQuote=()=>false;if(typeof window.printExactPdfPreview==="function")window.printExactPdfPreview=()=>false;if(typeof window.printQuote==="function")window.printQuote=()=>false;}
  function patchQuoteList(){if(typeof window.quoteRows!=="function"||window.__KPF_QUOTE_LIST_V3)return;window.__KPF_QUOTE_LIST_V3=true;const esc=v=>typeof window.esc==="function"?window.esc(v):String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money2=v=>typeof window.money==="function"?window.money(v):`${Math.round(num(v)).toLocaleString("hu-HU")} Ft`;window.quoteRows=function(arr){const rows=Array.isArray(arr)?arr:(db.quotes||[]),status=["Piszkozat","Elkészítve","Elküldve","Tárgyalás alatt","Elfogadva","Elutasítva","Lezárva"];const norm=q=>{const p=(db.projects||[]).find(x=>String(x.id)===String(q.projectId));const subject=String(q.subject??q.name??q.title??q.description??p?.name??"").trim();let depth=num(q.depth??q.wellDepth??q.talpDepth??p?.well?.depth??p?.depth);if(!depth){const m=subject.match(/(\d+(?:[.,]\d+)?)\s*m\b/i);depth=m?num(m[1]):0;}let dia=String(q.pipeDiameter??q.diameter??q.casingDiameter??projectPermitDiameter(p)??"");if(!dia){const m=subject.match(/(?:Ø\s*)?(\d+(?:[.,]\d+)?(?:\s*\/\s*\s*\d+(?:[.,]\d+)?)?)\s*mm\b/i);dia=m?m[1].replace(/\s+/g,""):"";}let net=num(q.net);if(!net)net=num(q.netTotal??q.totalNet)||((q.items||[]).reduce((s,x)=>s+num(x.qty??x.quantity)*num(x.price),0));let customer="";try{customer=typeof window.cust==="function"?String(window.cust(q.customerId)||""):"";}catch(e){}customer=customer||String(q.customerName??q.clientName??q.customer??"");const location=String(q.location??q.site??q.siteAddress??q.address??p?.location??p?.address??"");return {id:String(q.id??q.quoteNumber??q.number??""),subject,customer,location,depth,dia,net,status:String(q.status??"Piszkozat")};};return `<div class="tablewrap"><table class="table"><thead><tr><th>Ajánlat</th><th>Munka / megnevezés</th><th>Ügyfél</th><th>Helyszín</th><th>Fúrási mélység</th><th>Csőátmérő</th><th>Nettó</th><th>Státusz</th><th></th></tr></thead><tbody>${rows.map(q=>{const x=norm(q),d=x.depth?`${x.depth.toLocaleString("hu-HU",{minimumFractionDigits:1,maximumFractionDigits:1})} m`:"—",dia=x.dia?`Ø ${x.dia} mm`:"—";return `<tr><td><a href="#" class="link" onclick="openQuotePage('${esc(x.id)}');return false"><b>${esc(x.id)}</b></a></td><td>${esc(x.subject)}</td><td>${esc(x.customer)}</td><td>${esc(x.location)}</td><td>${d}</td><td>${esc(dia)}</td><td>${money2(x.net)}</td><td><select class="quote-status-pill" onchange="changeQuoteStatus('${esc(x.id)}',this.value)">${status.map(s=>`<option value="${esc(s)}" ${s===x.status?'selected':''}>${esc(s)}</option>`).join("")}</select></td><td><button class="btn secondary small" onclick="openQuoteEditorPage('${esc(x.id)}');return false;">Megnyitás</button>${x.status==="Elfogadva"?` <button class="btn small" onclick="convertQuote('${esc(x.id)}')">→ Projekt</button>`:""} <button class="btn danger small" onclick="deleteQuote('${esc(x.id)}');return false;">Törlés</button></td></tr>`;}).join("")}</tbody></table></div>`;};}
  function install(){normalizeProjectIds();ensurePipeCatalogIdentity();disablePreviewFunctions();removePreviewControls();installDocxModelGuard();patchExport();patchEditors();patchQuoteList();normalizeProjectUi();syncQuoteDiameterFromProject();syncQuoteCasingItemsFromProject();window.KUTFOPLUSZ_QUOTE_VISUAL_FIX=PATCH;window.KUTFOPLUSZ_PIPE_MATERIAL_IDENTITY=()=>({permitDiameter:projectPermitDiameter,index:ensurePipeCatalogIdentity});}
  install();window.addEventListener("load",install);window.addEventListener("hashchange",()=>setTimeout(install,0));setTimeout(install,300);setTimeout(install,1200);setTimeout(install,1800);
})();
