/* Kútfő Plusz ERP 2.0 — quote UI/DOCX compatibility layer */
(function(){
  "use strict";
  const PATCH="ERP2.0-PERMIT-DIAMETER-BINDING-FIX-2026-08-30-03";
  const getItems=()=>{try{if(typeof quoteItems!=="undefined"&&Array.isArray(quoteItems))return quoteItems;}catch(e){}return Array.isArray(window.quoteItems)?window.quoteItems:null;};
  function loadJSZip(urls,i){if(window.JSZip)return Promise.resolve(window.JSZip);i=i||0;if(i>=urls.length)return Promise.reject(new Error("JSZip nem tölthető be."));return new Promise((res,rej)=>{const s=document.createElement("script");s.src=urls[i];s.async=false;s.onload=()=>window.JSZip?res(window.JSZip):loadJSZip(urls,i+1).then(res,rej);s.onerror=()=>loadJSZip(urls,i+1).then(res,rej);document.head.appendChild(s);});}
  function ensureJSZip(){if(window.JSZip)return Promise.resolve(window.JSZip);if(window.__KUTFOPLUSZ_JSZIP_PROMISE)return window.__KUTFOPLUSZ_JSZIP_PROMISE;return window.__KUTFOPLUSZ_JSZIP_PROMISE=loadJSZip(["jszip.min.js","https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/dist/jszip.min.js","https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js"]);}
  function removePreviewControls(){document.querySelectorAll("button,a").forEach(el=>{const t=String(el.textContent||"").replace(/\s+/g," ").trim();if(/Előnézet\s*\/\s*PDF|PDF\s*\/\s*Nyomtatás|Nyomtatás\s*\/\s*PDF/i.test(t))el.remove();});}
  function disablePreviewFunctions(){if(typeof window.previewQuote==="function"&&!window.__KPF_preview){window.previewQuote=()=>{window.toast&&window.toast("A PDF/előnézet funkció ki van kapcsolva.");return false;};window.__KPF_preview=true;}if(typeof window.printExactPdfPreview==="function"&&!window.__KPF_printExact){window.printExactPdfPreview=()=>{window.toast&&window.toast("A PDF/előnézet funkció ki van kapcsolva.");return false;};window.__KPF_printExact=true;}if(typeof window.printQuote==="function"&&!window.__KPF_print){window.printQuote=()=>{window.toast&&window.toast("A PDF/nyomtatás funkció ki van kapcsolva. DOCX/ajánlat export használható.");return false;};window.__KPF_print=true;}}
  function normalizeProjectIds(){try{if(typeof db==="undefined"||!db||!Array.isArray(db.projects))return;let ch=false;const ids=new Map();db.projects.forEach(p=>{if(!p||p.id==null)return;const n=String(p.id);ids.set(n,n);if(p.id!==n){p.id=n;ch=true;}});["quotes","worklogs","documents","services","purchases","stockMovements","invoices"].forEach(k=>(Array.isArray(db[k])?db[k]:[]).forEach(r=>["projectId","sourceProjectId","linkedProjectId"].forEach(f=>{if(r&&r[f]!=null){const n=ids.get(String(r[f]));if(n&&r[f]!==n){r[f]=n;ch=true;}}})));if(ch&&typeof save==="function")save();}catch(e){console.warn(e);}}
  function currentProject(){try{let pid=window.projectPageId||(typeof db!=="undefined"&&db?.ui?.openProjectId);if(!pid){const r=String(location.hash||"").replace(/^#\//,"");if(r.indexOf("project/")===0)pid=decodeURIComponent(r.split("/")[1]||"");}return typeof db!=="undefined"&&Array.isArray(db.projects)&&pid?db.projects.find(p=>String(p.id)===String(pid))||null:null;}catch(e){return null;}}
  function acceptedQuoteForProject(p){try{const q=(Array.isArray(db?.quotes)?db.quotes:[]).filter(x=>String(x.projectId||"")===String(p?.id)).filter(x=>String(x.status||"")==="Elfogadva");return q.length?q[q.length-1]:null;}catch(e){return null;}}
  function projectContractValue(p){const q=acceptedQuoteForProject(p);if(q&&typeof window.quoteNetValue==="function")return Number(window.quoteNetValue(q))||0;if(q)return Number(q.netTotal||q.net||0)||0;return Number(p?.value)||0;}
  function normalizeDiameterText(text){let s=String(text||"").replace(/\s+/g," ").trim().replace(/\s*Ø\s*/gi," ").replace(/\s*mm\b/gi," mm");const m=s.match(/(?:^|\s)(\d+(?:[.,]\d+)?(?:\s*\/\s*\s*\d+(?:[.,]\d+)?)?)\s*mm\b/i);if(!m)return s;const d=m[1].replace(/\s+/g,"").replace(/,/g,".");return(s.slice(0,m.index||0).trim()+" Ø "+d+" mm "+s.slice((m.index||0)+m[0].length).trim()).replace(/\s+/g," ").trim();}
  function normalizeProjectUi(){const p=currentProject(),box=document.querySelector(".project-hero-kpis");if(!p||!box)return;const h=document.querySelector("h1");if(h&&/\d+(?:[.,]\d+)?(?:\s*\/\s*\d+(?:[.,]\d+)?)?\s*Ø?\s*mm\b/i.test(h.textContent||""))h.textContent=normalizeDiameterText(h.textContent);const cards=[...box.querySelectorAll(":scope > .card")];if(cards.length<4)return;const contract=projectContractValue(p),cost=Number(p.cost)||0,vals=[(Number(p.progress)||0)+"%",window.money?window.money(contract):contract.toLocaleString("hu-HU")+" Ft",window.money?window.money(cost):cost.toLocaleString("hu-HU")+" Ft",window.money?window.money(contract-cost):(contract-cost).toLocaleString("hu-HU")+" Ft"],labs=["Készültség","Szerződéses érték","Tényleges költség","Fedezet"];cards.forEach((c,i)=>{c.querySelector(".label")&&(c.querySelector(".label").textContent=labs[i]);c.querySelector(".value")&&(c.querySelector(".value").textContent=vals[i]);});}
  function normalizeRole(v){const s=String(v??"").trim().toLowerCase();if(/szűr|szuro|filter/.test(s))return "FILTER";if(/termelő|termelo|production/.test(s))return "PRODUCTION";return "BLANK";}
  function normalizeProdDiameter(v){const s=String(v??"").trim().replace(/\s+/g,"");return s==='3'?'3"':s==='4'?'4"':s.includes('"')?s:s+'"';}
  function parseMaterialDiameter(name){const s=String(name||"").replace(/,/g,".");const m=s.match(/(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)\s*mm/i);if(m)return m[1].replace(/\s+/g,"");const n=s.match(/(\d+(?:\.\d+)?)\s*mm/i);return n?n[1]:"";}
  function canonicalMaterialIdentity(material){const m=material||{};if(m.materialKey)return String(m.materialKey);const role=/szűr|szuro|filter/i.test(String(m.pipeType||"")+" "+String(m.name||""))?"FILTER":/termelő|termelo|production/i.test(String(m.pipeType||"")+" "+String(m.name||""))?"PRODUCTION":"BLANK";const d=parseMaterialDiameter(m.name);if(!d)return "";if(role==="PRODUCTION"){const pd=normalizeProdDiameter(m.productionPipeDiameter||m.diameter||"");return pd&&pd!=="\""?`PRODUCTION|${pd}|BLANK`:"";}return `CASING|${d}|${role}`;}
  function projectPermitDiameter(project){try{const w=project?.well||{},sections=Array.isArray(w.casingSections)?w.casingSections:[];for(const sec of sections){const candidates=[sec?.diameter,sec?.pipeDiameter,sec?.casingDiameter,sec?.technicalData,sec?.technical,sec?.spec,sec?.[3]];for(const raw of candidates){const s=String(raw??'').replace(/,/g,'.');const m=s.match(/(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)\s*Ø?\s*mm/i);if(m)return m[1].replace(/\s+/g,'');const n=s.match(/(?:Ø\s*)?(\d+(?:\.\d+)?)\s*mm/i);if(n)return n[1];}}for(const raw of [project?.name,project?.title,project?.description]){const s=String(raw??'').replace(/,/g,'.');const m=s.match(/(\d+(?:\.\d+)?\s*\/\s*\d+(?:\.\d+)?)\s*Ø?\s*mm/i);if(m)return m[1].replace(/\s+/g,'');}const d=w.casingDiameter??w.védőcsőÁtmérő??project?.casingDiameter;return d!=null?String(d).replace(/,/g,'.').replace(/\s+/g,''):'';}catch(e){return '';}}
  function syncQuoteDiameterFromProject(){try{const el=document.getElementById("q_pipe_diameter"),pe=document.getElementById("q_project");if(!el||!pe||typeof db==="undefined")return;const p=(Array.isArray(db.projects)?db.projects:[]).find(x=>String(x.id)===String(pe.value||""));if(!p)return;const full=projectPermitDiameter(p);if(!full)return;const numeric=String(full).split('/')[0].trim();if(el.tagName==='SELECT'){let opt=[...el.options].find(o=>String(o.value)===numeric||String(o.dataset.fullDiameter||'')===full);if(!opt){opt=document.createElement('option');el.appendChild(opt);}opt.value=numeric;opt.textContent=`Ø ${full} mm`;opt.dataset.fullDiameter=full;el.value=numeric;el.dataset.fullDiameter=full;}else{el.value=full;el.dataset.numericDiameter=numeric;el.dataset.fullDiameter=full;}el.dispatchEvent(new Event('change',{bubbles:true}));if(typeof window.recalculateQuoteMainItem==='function')window.recalculateQuoteMainItem(false);}catch(e){console.warn("Ajánlat átmérő szinkron:",e);}}
  function syncQuoteCasingItemsFromProject(){try{const items=getItems(),pe=document.getElementById("q_project");if(!items||!pe||typeof db==="undefined")return;const p=(Array.isArray(db.projects)?db.projects:[]).find(x=>String(x.id)===String(pe.value||""));if(!p)return;const sections=Array.isArray(p.well?.casingSections)?p.well.casingSections:[];if(!sections.length)return;ensurePipeCatalogIdentity();const norm=v=>normalizeRole(v)==="FILTER"?"Szűrő":"Vak";const meters=type=>sections.filter(s=>norm(s.type??s[2])===type).reduce((a,s)=>a+Math.max(0,(Number(s.to??s[1])||0)-(Number(s.from??s[0])||0)),0);const upsert=(type,count)=>{if(count<=0)return;const role=type==="Szűrő"?"FILTER":"BLANK",key=`CASING|${projectPermitDiameter(p)||324}|${role}`,resolved=exactCatalogMaterial(p,{type}),tag=role==="FILTER"?"__KPF_CASING_FILTER":"__KPF_CASING_BLANK";let item=items.find(x=>x&&x[tag]);if(!item){item={name:"",quantity:0,unit:"m",price:0};items.push(item);}item[tag]=true;item.materialKey=key;item.casingMaterialKey=key;item.name=resolved.material?.name||`PVC ${type==='Szűrő'?"szűrőcső":"béléscső"} Ø${projectPermitDiameter(p)||324} mm`;item.quantity=count;item.qty=count;item.unit="m";if(!item.priceManual){if(resolved.material&&Number(resolved.material.price)>0){item.price=Number(resolved.material.price);item.priceMissing=false;item.priceSource="catalog-exact";}else{item.price=0;item.priceMissing=true;item.priceSource="catalog-missing";}}};upsert("Vak",meters("Vak"));upsert("Szűrő",meters("Szűrő"));if(typeof window.renderQuoteItems==="function")window.renderQuoteItems();else if(typeof window.renderQuoteEditor==="function")window.renderQuoteEditor();else if(typeof window.renderQuotePage==="function")window.renderQuotePage();if(typeof window.recalculateQuoteTotals==="function")window.recalculateQuoteTotals();else if(typeof window.recalculateQuoteMainItem==="function")window.recalculateQuoteMainItem();}catch(e){console.warn("Ajánlat csövezés/szűrőzés szinkron:",e);}}
  function sectionIdentity(project,section){const d=projectPermitDiameter(project)||'324';const role=normalizeRole(section?.type??section?.[2]);return `CASING|${d}|${role}`;}
  function ensurePipeCatalogIdentity(){try{if(typeof db==="undefined"||!db)return;const rows=Array.isArray(db.materials)?db.materials:[];let changed=false;rows.forEach(m=>{if(!m||!m.name)return;const key=canonicalMaterialIdentity(m);if(key&&m.materialKey!==key){m.materialKey=key;changed=true;}if(key&&/^CASING\|/.test(key)&&m.casingMaterialKey!==key){m.casingMaterialKey=key;changed=true;}});if(changed&&typeof save==="function")save();const idx={};rows.forEach(m=>{const k=canonicalMaterialIdentity(m);if(k)idx[k]=m;});window.KUTFOPLUSZ_PIPE_CATALOG_INDEX=idx;return idx;}catch(e){console.warn("Csőanyag-katalógus identitás:",e);return {};}}
  function exactCatalogMaterial(project,section){const key=sectionIdentity(project,section),idx=ensurePipeCatalogIdentity()||{};return {key,material:idx[key]||null};}
  function stripLeadingQuantityUnit(desc,item){let s=String(desc??"").replace(/\s+/g," ").trim();const q=Number(item?.qty??item?.quantity),u=String(item?.unit||"").trim();if(!s||!Number.isFinite(q)||!u)return s;const qt=String(q).replace(/\.0+$/,'');const eu=u.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return s.replace(new RegExp('^'+qt+'\\s*(?:×|x|db|'+eu+')\\s+','i'),'').trim();}
  function installDocxModelGuard(){if(window.__KPF_DOCX_GUARD||typeof window.collectQuoteTemplate!=="function")return;window.__KPF_DOCX_GUARD=true;const original=window.collectQuoteTemplate;window.collectQuoteTemplate=function(){const model=original.apply(this,arguments);try{model?.items?.forEach(i=>{if(i&&i.desc!=null)i.desc=stripLeadingQuantityUnit(i.desc,i);});}catch(e){}return model;};}
  function installManualTracking(){if(window.__KPF_MANUAL)return;window.__KPF_MANUAL=true;document.addEventListener("input",e=>{const t=e.target,row=t?.closest?.("#q_items tr"),items=getItems();if(!row||!items)return;const i=[...document.querySelectorAll("#q_items tr")].indexOf(row);if(i>=0&&items[i]&&row.children[3]?.contains(t))items[i].priceManual=true;},{capture:true});}
  function patchExport(){if(window.__KPF_EXPORT)return;window.__KPF_EXPORT=true;window.customerId=window.customerId??null;if(typeof window.exportQuoteDoc==="function"){const o=window.exportQuoteDoc;window.exportQuoteDoc=function(){try{const a=arguments[0],q=a&&typeof a==="object"?a:(typeof db!=="undefined"?db?.quotes?.find(x=>String(x.id)===String(a)):null);if(q?.customerId!=null)window.customerId=q.customerId;}catch(e){}return o.apply(this,arguments);};}}
  function patchQuoteEditorOpen(){if(window.__KPF_QUOTE_EDITOR_OPEN||typeof window.openQuoteEditorPage!=="function")return;window.__KPF_QUOTE_EDITOR_OPEN=true;const original=window.openQuoteEditorPage;window.openQuoteEditorPage=function(){const r=original.apply(this,arguments);setTimeout(()=>{syncQuoteDiameterFromProject();syncQuoteCasingItemsFromProject();},80);setTimeout(()=>{syncQuoteDiameterFromProject();},500);return r;};}
  function patch(){normalizeProjectIds();ensurePipeCatalogIdentity();disablePreviewFunctions();installDocxModelGuard();installManualTracking();patchExport();normalizeProjectUi();patchQuoteEditorOpen();syncQuoteDiameterFromProject();syncQuoteCasingItemsFromProject();if(typeof window.openProjectPage==="function"&&!window.__KPF_PROJECT_NAV){const o=window.openProjectPage;window.openProjectPage=function(){normalizeProjectIds();const r=o.apply(this,arguments);setTimeout(normalizeProjectUi,0);return r;};window.__KPF_PROJECT_NAV=true;}if(typeof window.openQuotePage==="function"&&!window.__KPF_QUOTE_OPEN){const o=window.openQuotePage;window.openQuotePage=function(){const r=o.apply(this,arguments);setTimeout(()=>{removePreviewControls();disablePreviewFunctions();syncQuoteDiameterFromProject();syncQuoteCasingItemsFromProject();installDocxModelGuard();},80);return r;};window.__KPF_QUOTE_OPEN=true;}removePreviewControls();}
  window.KUTFOPLUSZ_QUOTE_VISUAL_FIX=PATCH;window.KUTFOPLUSZ_PIPE_MATERIAL_IDENTITY=()=>({index:ensurePipeCatalogIdentity(),resolve:exactCatalogMaterial,permitDiameter:projectPermitDiameter});patch();window.addEventListener("load",patch);window.addEventListener("hashchange",()=>setTimeout(patch,0));setTimeout(patch,300);setTimeout(patch,1200);setTimeout(patch,1800);
})();

/* ERP2.0-QUOTE-LIST-NORMALIZED-2026-08-30 */
(function(){
  "use strict";
  const n=v=>{if(v===null||v===undefined||v==='')return NaN;const x=Number(String(v).replace(/\s/g,'').replace(',','.'));return Number.isFinite(x)?x:NaN;};
  const esc2=v=>typeof window.esc==='function'?window.esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money2=v=>typeof window.money==='function'?window.money(v):`${Math.round(n(v)||0).toLocaleString('hu-HU')} Ft`;
  const items=q=>Array.isArray(q?.items)?q.items:[];
  const itemNet=q=>items(q).reduce((s,x)=>s+(n(x?.qty??x?.quantity??x?.count)||0)*(n(x?.price??x?.unitPrice??x?.unitPriceNet)||0),0);
  const project=q=>{try{const id=q?.projectId??q?.sourceProjectId??q?.linkedProjectId;return id!=null?(db.projects||[]).find(p=>String(p.id)===String(id))||null:null;}catch(e){return null;}};
  const depthText=s=>{const m=String(s??'').replace(',','.').match(/(\d+(?:\.\d+)?)\s*m\b/i);return m?n(m[1]):NaN;};
  const diameterText=s=>{const m=String(s??'').replace(',','.').match(/(?:Ø\s*)?(\d+(?:\.\d+)?(?:\s*\/\s*\s*\d+(?:\.\d+)?)?)\s*mm\b/i);return m?m[1].replace(/\s+/g,''):'';};
  const normalized=q=>{const p=project(q),subject=String(q?.subject??q?.name??q?.title??q?.description??p?.name??'').trim();let depth=n(q?.depth??q?.wellDepth??q?.talpDepth??p?.well?.depth??p?.depth);if(!Number.isFinite(depth)||depth<=0)depth=depthText(subject);let diameter=String(q?.pipeDiameter??q?.diameter??q?.casingDiameter??'').trim();if(!diameter&&p&&typeof window.KUTFOPLUSZ_PIPE_MATERIAL_IDENTITY==='function'){try{diameter=String(window.KUTFOPLUSZ_PIPE_MATERIAL_IDENTITY().permitDiameter(p)||'');}catch(e){}}if(!diameter)for(const x of items(q)){diameter=diameterText(x?.desc??x?.description??x?.name);if(diameter)break;}if(!diameter)diameter=diameterText(subject);let net=n(q?.net);if(!Number.isFinite(net)||net<0)net=NaN;if(!Number.isFinite(net)||net===0){const stored=n(q?.netTotal??q?.totalNet);net=Number.isFinite(stored)&&stored>0?stored:itemNet(q);}net=Math.round((net||0)*100)/100;let gross=n(q?.gross??q?.grossTotal??q?.totalGross);if(!Number.isFinite(gross)||gross<0)gross=Math.round(net*1.27);if(gross===0&&net>0)gross=Math.round(net*1.27);let customer='';try{customer=typeof window.cust==='function'?String(window.cust(q?.customerId)||''):'';}catch(e){}if(!customer)customer=String(q?.customerName??q?.clientName??q?.customer??'');const location=String(q?.location??q?.site??q?.siteAddress??q?.address??p?.location??p?.address??'').trim();return {q,p,id:String(q?.id??q?.quoteNumber??q?.number??''),name:subject,customer,location,depth,diameter,net,gross,status:String(q?.status??'Piszkozat')};};
  const patch=()=>{if(typeof window.quoteRows!=='function'||window.__KPF_QUOTE_LIST_V2)return;window.quoteRows=function(arr){const rows=Array.isArray(arr)?arr:(db.quotes||[]),statuses=["Piszkozat","Elkészítve","Elküldve","Tárgyalás alatt","Elfogadva","Elutasítva","Lezárva"];return `<div class="tablewrap"><table class="table"><thead><tr><th>Ajánlat</th><th>Ügyfél</th><th>Helyszín</th><th>Fúrási mélység</th><th>Csőátmérő</th><th>Nettó</th><th>Státusz</th><th></th></tr></thead><tbody>${rows.map(q=>{const x=normalized(q),d=Number.isFinite(x.depth)?`${x.depth.toLocaleString('hu-HU',{minimumFractionDigits:1,maximumFractionDigits:1})} m`:'—',dia=x.diameter?`Ø ${x.diameter} mm`:'—';return `<tr><td><a href="#" class="link" data-quote-id="${esc2(x.id)}" onclick="openQuotePage('${esc2(x.id)}');return false" title="Árajánlat megnyitása"><b>${esc2(x.id)}</b></a><br><span class="label">${esc2(x.name)}</span></td><td>${esc2(x.customer)}</td><td>${esc2(x.location)}</td><td>${d}</td><td>${esc2(dia)}</td><td>${money2(x.net)}</td><td><select class="quote-status-pill quote-status-${typeof window.statusClass==='function'?window.statusClass(x.status):'draft'}" onchange="changeQuoteStatus('${esc2(x.id)}',this.value)" aria-label="Státusz">${statuses.map(st=>`<option value="${esc2(st)}" ${x.status===st?'selected':''}>${esc2(st)}</option>`).join('')}</select></td><td style="white-space:nowrap"><div style="display:flex;gap:6px;align-items:center;justify-content:flex-end"><button class="btn secondary small" onclick="openQuoteEditorPage('${esc2(x.id)}');return false;">Megnyitás</button>${x.status==='Elfogadva'?`<button class="btn small" onclick="convertQuote('${esc2(x.id)}')">→ Projekt</button>`:''}<button class="btn danger small" onclick="deleteQuote('${esc2(x.id)}');return false;">Törlés</button></div></td></tr>`;}).join('')}</tbody></table></div>`;};if(typeof window.quoteNetValue==='function'&&!window.__KPF_QUOTE_NET_V2){window.quoteNetValue=function(q){const direct=n(q?.net);if(Number.isFinite(direct)&&direct>0)return direct;const legacy=n(q?.netTotal??q?.totalNet);if(Number.isFinite(legacy)&&legacy>0)return legacy;const calc=itemNet(q);return Number.isFinite(calc)?calc:0;};window.__KPF_QUOTE_NET_V2=true;}window.__KPF_QUOTE_LIST_V2=true;if(location.hash==='#/quotes'&&typeof window.nav==='function')setTimeout(()=>window.nav('quotes'),0);};patch();window.addEventListener('load',patch);window.addEventListener('hashchange',()=>setTimeout(patch,0));setTimeout(patch,300);setTimeout(patch,1200);
})();

/* ERP2.0-QUOTE-NUMBER-CANONICAL-2026-08-30 */
(function(){
  "use strict";
  const install=()=>{if(typeof window.nextQuoteId!=='function'||window.__KPF_QUOTE_NUMBER_V2)return;if(typeof window.nextDocumentSequence!=='function'&&typeof nextDocumentSequence!=='function')return;window.nextQuoteId=function(){const yy=String(new Date().getFullYear()).slice(-2);const seq=String(typeof window.nextDocumentSequence==='function'?window.nextDocumentSequence():nextDocumentSequence()).padStart(3,'0');return `A-${yy}-${seq}`;};window.__KPF_QUOTE_NUMBER_V2=true;};
  install();window.addEventListener('load',install);setTimeout(install,100);setTimeout(install,500);setTimeout(install,1200);
})();

/* ERP2.0-QUOTE-EDITOR-PRESERVE-2026-08-30 */
(function(){
  "use strict";
  const install=()=>{
    if(typeof window.editQuote!=='function'||window.__KPF_QUOTE_EDIT_PRESERVE)return;
    const original=window.editQuote;
    window.editQuote=function(id){
      const q=(typeof db!=='undefined'&&Array.isArray(db.quotes))?db.quotes.find(x=>String(x.id)===String(id)):null;
      const snapshot=q&&Array.isArray(q.items)?q.items.map(x=>({...x})):null;
      const r=original.apply(this,arguments);
      if(q&&snapshot)setTimeout(()=>{try{
        if(Array.isArray(window.quoteItems))window.quoteItems=snapshot.map(x=>({desc:String(x.desc??x.description??''),qty:Number(x.qty??x.quantity??x.count)||0,unit:String(x.unit??x.unitName??'db'),price:Number(x.price??x.unitPrice??x.unitPriceNet)||0,priceManual:!!x.priceManual,autoCalculated:!!x.autoCalculated}));
        const d=document.getElementById('q_depth');if(d&&q.depth!=null)d.value=q.depth;
        const e=document.getElementById('q_pipe_diameter');if(e&&q.pipeDiameter!=null){const value=String(q.pipeDiameter),numeric=value.split('/')[0].trim();if(e.tagName==='SELECT'&&!Array.from(e.options).some(o=>String(o.value)===numeric)){const opt=document.createElement('option');opt.value=numeric;opt.textContent=`Ø ${value} mm`;opt.dataset.fullDiameter=value;e.appendChild(opt);}e.value=e.tagName==='SELECT'?numeric:value;}
        if(typeof window.renderQuoteItems==='function')window.renderQuoteItems();else if(typeof window.renderQuoteEditor==='function')window.renderQuoteEditor();
        if(typeof window.recalculateQuoteTotals==='function')window.recalculateQuoteTotals();else if(typeof window.recalculateQuote==='function')window.recalculateQuote();
      }catch(e){console.warn('Ajánlat szerkesztő adat-visszaállítás:',e);}},120);
      return r;
    };
    window.__KPF_QUOTE_EDIT_PRESERVE=true;
  };
  install();window.addEventListener('load',install);setTimeout(install,100);setTimeout(install,500);setTimeout(install,1200);setTimeout(install,2000);
})();

/* smoke-regression-trigger: quote list */
