/* Kútfő Plusz ERP 2.0 – PDF preview: fullscreen A4 viewer */
(function(){
  "use strict";
  const PATCH="ERP2.0-QUOTE-PREVIEW-FULLSCREEN-A4-2026-08-29-02";
  let raf=0;
  function appLogoSrc(){const imgs=[...document.images].filter(img=>!img.closest(".qv-page")&&img.complete&&img.naturalWidth>0);const hit=imgs.find(img=>/kutf|kút|plusz|logo/.test((String(img.alt||"")+" "+String(img.src||"")).toLowerCase()));return hit?hit.src:"";}
  function findModal(page){let el=page,dialog=null,content=null,body=null;for(let i=0;i<14&&el;i++,el=el.parentElement){if(!body&&(el.classList?.contains("modalbody")||el.classList?.contains("modal-body")||el.getAttribute?.("data-modal-body")==="true"))body=el;if(!content&&(el.classList?.contains("modalbox")||el.classList?.contains("modal-content")))content=el;if(!dialog&&(el.classList?.contains("modal")||el.classList?.contains("modal-dialog")||el.getAttribute?.("role")==="dialog"))dialog=el;}return{dialog,content,body};}
  function injectFullscreenStyle(){if(document.getElementById("kutfo-quote-preview-fullscreen-style"))return;const s=document.createElement("style");s.id="kutfo-quote-preview-fullscreen-style";s.textContent=`body:has(.qv-page) .modal{padding:0!important;place-items:stretch!important}body:has(.qv-page) .modalbox{width:100vw!important;max-width:none!important;height:100vh!important;max-height:none!important;border-radius:0!important;overflow:hidden!important;display:flex!important;flex-direction:column!important}body:has(.qv-page) .modalhead{flex:0 0 auto!important}body:has(.qv-page) .modalbody{flex:1 1 auto!important;min-height:0!important;height:auto!important;max-height:none!important;overflow:auto!important;-webkit-overflow-scrolling:touch!important;padding:12px 24px!important;background:#f3f4f6!important}body:has(.qv-page) .modalfoot{flex:0 0 auto!important;margin-top:0!important;padding:10px 0!important}body:has(.qv-page) .modalbody .qv-page{margin-bottom:16px!important}`;document.head.appendChild(s);}
  function fitPage(page){if(!page||!page.isConnected)return;const m=findModal(page);const naturalW=page.offsetWidth||page.scrollWidth||1020;const bodyW=m.body?.clientWidth||window.innerWidth;const availableW=Math.max(300,bodyW-48);const scale=Math.min(1,availableW/naturalW);page.style.transformOrigin="top center";page.style.transform=scale<1?"scale("+scale+")":"none";page.style.width=naturalW+"px";page.style.height="auto";page.style.margin="0 auto 16px";page.style.marginBottom="16px";page.style.flex="0 0 auto";page.style.boxSizing="border-box";page.dataset.kutfoPreviewScale=String(scale);}
  function fitModal(page){const m=findModal(page);if(m.dialog){m.dialog.style.width="100vw";m.dialog.style.maxWidth="100vw";m.dialog.style.height="100vh";m.dialog.style.maxHeight="100vh";m.dialog.style.margin="0";m.dialog.style.padding="0";}if(m.content){m.content.style.width="100vw";m.content.style.maxWidth="100vw";m.content.style.height="100vh";m.content.style.maxHeight="100vh";m.content.style.margin="0";m.content.style.borderRadius="0";m.content.style.overflow="hidden";m.content.style.display="flex";m.content.style.flexDirection="column";}if(m.body){m.body.style.flex="1 1 auto";m.body.style.minHeight="0";m.body.style.height="auto";m.body.style.maxHeight="none";m.body.style.overflow="auto";m.body.style.width="100%";m.body.style.boxSizing="border-box";}}
  function repairLogo(page){const src=appLogoSrc(),imgs=page.querySelectorAll("img");if(!src||!imgs.length)return;const logo=imgs[0];logo.src=src;logo.removeAttribute("srcset");logo.style.background="transparent";logo.style.objectFit="contain";}
  function run(){injectFullscreenStyle();document.querySelectorAll(".qv-page").forEach(function(page){fitModal(page);fitPage(page);repairLogo(page);});}
  function schedule(){if(raf)return;raf=requestAnimationFrame(function(){raf=0;run();});}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("resize",schedule);window.addEventListener("load",schedule);window.KUTFOPLUSZ_QUOTE_PREVIEW_VIEWPORT_FIX=PATCH;schedule();
})();
